# Generated by Django 5.1 on 2025-04-23 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0005_post_reviewer_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_assigned', models.CharField(max_length=100)),
                ('section_assigned', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_date', models.DateField()),
                ('records_maintenance_personnel', models.CharField(max_length=100)),
                ('records_maintenance_date', models.DateField()),
                ('date_reviewed', models.DateField(auto_now_add=True)),
                ('signature', models.CharField(max_length=10)),
                ('qa_review_date', models.DateField(blank=True, null=True)),
                ('qa_signature', models.CharField(blank=True, max_length=10)),
                ('printed_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('qa_printed_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
