# Generated by Django 5.1 on 2025-05-06 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0006_trainingrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='printed_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='qa_printed_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
