# Generated by Django 4.2.9 on 2025-05-07 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0007_remove_trainingrecord_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 7, 12, 39, 42, 698803, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
